# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)
android_dir = File.expand_path('../android')

#
#  Figure out the latest google play version code
#
def latest_googleplay_version_code
  begin
    productionVersionCodes = google_play_track_version_codes(track: 'production')
  rescue StandardError => e
    productionVersionCodes = []
  end

  begin
    betaVersionCodes = google_play_track_version_codes(track: 'beta')
  rescue StandardError => e
    betaVersionCodes = []
  end

  begin
    alphaVersionCodes = google_play_track_version_codes(track: 'alpha')
  rescue StandardError => e
    alphaVersionCodes = []
  end

  begin
    internalVersionCodes = google_play_track_version_codes(track: 'internal')
  rescue StandardError => e
    internalVersionCodes = []
  end

  # puts version codes from all tracks into the same array
  versionCodes = [
    productionVersionCodes,
    betaVersionCodes,
    alphaVersionCodes,
    internalVersionCodes
  ].reduce([], :concat)

  # returns the highest version code from array
  return versionCodes.max
end

#
# Update version code
#

def set_version_code(new_version_code)
  file_name = File.expand_path("../android/app/build.gradle")
  current_content = File.read(file_name)
  new_content = current_content.gsub(/(versionCode\s[0-9]+)/, "versionCode #{new_version_code}")
  File.write(file_name, new_content)
end

#
# Build and release logic
#
def build_and_release(track)
  # Get previous build number and increment
  current_build_number = latest_googleplay_version_code() + 10
  set_version_code(current_build_number)

  gradle(
    task: "clean bundleRelease",
    project_dir: android_dir,
    properties: {
      'android.injected.signing.store.file' => File.expand_path('../open-pulse.keystore'),
      'android.injected.signing.store.password' => ENV['KEYSTORE_STORE_PASSWORD'],
      'android.injected.signing.key.alias' => ENV['KEYSTORE_KEY_ALIAS'],
      'android.injected.signing.key.password' => ENV['KEYSTORE_KEY_PASSWORD'],
      "android.injected.version.code" => current_build_number,
    }
  )

  upload_to_play_store(
    track: track,
    release_status: "completed",  # TODO: set to completed once app is released
    version_code: current_build_number,
  )
end

#
# Android platform lanes
#

platform :android do
  desc "Verify changelog exists"
  private_lane :verify_changelog_exists do |version_code: |
    changelog_path = "android/metadata/en-US/changelogs/#{version_code}.txt"
    UI.user_error!("Missing changelog file at #{changelog_path}") unless File.exist?(changelog_path)
    UI.message("Changelog exists for version code #{version_code}")
  end

  desc "Runs all the tests"
  lane :test do
      gradle(task: "test", project_dir: android_dir)
  end

  desc "Submit a new build to Play Store internal testing"
  lane :internal do
    build_and_release("internal")
  end

  desc "Submit a new build to Play Store beta testing"
  lane :beta do
    build_and_release("beta")
  end

  desc "Submit a new build to Play Store alpha testing"
  lane :alpha do
    build_and_release("alpha")
  end

  desc "Submit a new build to Play store production"
  lane :production do
    build_and_release("production")
  end
end
